services:
  client-backend:
    image: springio/gs-spring-boot-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/devBooks
      - SPRING_FLYWAY_URL=jdbc:postgresql://service-db/devBooks

  service-db:
    image: postgres:14.8-alpine3.18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "devBooks"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    restart: unless-stopped
